repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-kash_logo_light.png
    - docs/images/nf-core-kash_logo_light.png
    - docs/images/nf-core-kash_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-kash_logo_light.png
    - docs/images/nf-core-kash_logo_light.png
    - docs/images/nf-core-kash_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge
  included_configs: false

template:
  org: yumyai
  name: kash
  description: Amplicon pipeline
  author: Preecha Patumcharoenpol
  version: 0.1.0dev
  force: true
  outdir: kash
  skip_features:
    - igenomes
    - github_badges
    - nf_core_configs
    - gitpod
    - codespaces
    - fastqc
    - adaptivecard
    - slackreport
    - seqera_platform
    - rocrate
  is_nfcore: false
