name: "emu_mark_negative"
description: Post-process EMU relative abundance outputs to flag known bacteria from negative.
keywords:
- metagenomics
- pathogen
- reporting
tools:
- mark_pathogen:
    description: Summaries EMU abundance tables and flags known pathogens.
    documentation: https://github.com/yumyai/kash/blob/main/bin/mark_pathogen.py
    licence: ["MIT"]
input:
- - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - rel_abundance:
      type: file
      description: EMU relative abundance file (*.tsv)
      pattern: "*_rel-abundance.tsv"
output:
- report:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - '*.tsv':
      type: file
      description: Report highlighting known pathogens per sample.
- versions:
  - versions.yml:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
- "@codex-gpt5"
